// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_common.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_pb_5fcommon_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_pb_5fcommon_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_pb_5fcommon_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_pb_5fcommon_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_pb_5fcommon_2eproto;
namespace pb_common {
class req_head;
struct req_headDefaultTypeInternal;
extern req_headDefaultTypeInternal _req_head_default_instance_;
class req_test;
struct req_testDefaultTypeInternal;
extern req_testDefaultTypeInternal _req_test_default_instance_;
}  // namespace pb_common
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace pb_common {

// ===================================================================


// -------------------------------------------------------------------

class req_test final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb_common.req_test) */ {
 public:
  inline req_test() : req_test(nullptr) {}
  ~req_test() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR req_test(::google::protobuf::internal::ConstantInitialized);

  inline req_test(const req_test& from)
      : req_test(nullptr, from) {}
  req_test(req_test&& from) noexcept
    : req_test() {
    *this = ::std::move(from);
  }

  inline req_test& operator=(const req_test& from) {
    CopyFrom(from);
    return *this;
  }
  inline req_test& operator=(req_test&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const req_test& default_instance() {
    return *internal_default_instance();
  }
  static inline const req_test* internal_default_instance() {
    return reinterpret_cast<const req_test*>(
               &_req_test_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(req_test& a, req_test& b) {
    a.Swap(&b);
  }
  inline void Swap(req_test* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(req_test* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  req_test* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<req_test>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const req_test& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const req_test& from) {
    req_test::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(req_test* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "pb_common.req_test";
  }
  protected:
  explicit req_test(::google::protobuf::Arena* arena);
  req_test(::google::protobuf::Arena* arena, const req_test& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kN1FieldNumber = 1,
  };
  // optional int32 n1 = 1;
  bool has_n1() const;
  void clear_n1() ;
  ::int32_t n1() const;
  void set_n1(::int32_t value);

  private:
  ::int32_t _internal_n1() const;
  void _internal_set_n1(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:pb_common.req_test)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t n1_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pb_5fcommon_2eproto;
};// -------------------------------------------------------------------

class req_head final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb_common.req_head) */ {
 public:
  inline req_head() : req_head(nullptr) {}
  ~req_head() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR req_head(::google::protobuf::internal::ConstantInitialized);

  inline req_head(const req_head& from)
      : req_head(nullptr, from) {}
  req_head(req_head&& from) noexcept
    : req_head() {
    *this = ::std::move(from);
  }

  inline req_head& operator=(const req_head& from) {
    CopyFrom(from);
    return *this;
  }
  inline req_head& operator=(req_head&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const req_head& default_instance() {
    return *internal_default_instance();
  }
  static inline const req_head* internal_default_instance() {
    return reinterpret_cast<const req_head*>(
               &_req_head_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(req_head& a, req_head& b) {
    a.Swap(&b);
  }
  inline void Swap(req_head* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(req_head* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  req_head* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<req_head>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const req_head& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const req_head& from) {
    req_head::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(req_head* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "pb_common.req_head";
  }
  protected:
  explicit req_head(::google::protobuf::Arena* arena);
  req_head(::google::protobuf::Arena* arena, const req_head& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProtocolCodeFieldNumber = 1,
    kDataLenFieldNumber = 2,
  };
  // optional int32 protocol_code = 1;
  bool has_protocol_code() const;
  void clear_protocol_code() ;
  ::int32_t protocol_code() const;
  void set_protocol_code(::int32_t value);

  private:
  ::int32_t _internal_protocol_code() const;
  void _internal_set_protocol_code(::int32_t value);

  public:
  // optional int32 data_len = 2;
  bool has_data_len() const;
  void clear_data_len() ;
  ::int32_t data_len() const;
  void set_data_len(::int32_t value);

  private:
  ::int32_t _internal_data_len() const;
  void _internal_set_data_len(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:pb_common.req_head)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t protocol_code_;
    ::int32_t data_len_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pb_5fcommon_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// req_head

// optional int32 protocol_code = 1;
inline bool req_head::has_protocol_code() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void req_head::clear_protocol_code() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.protocol_code_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t req_head::protocol_code() const {
  // @@protoc_insertion_point(field_get:pb_common.req_head.protocol_code)
  return _internal_protocol_code();
}
inline void req_head::set_protocol_code(::int32_t value) {
  _internal_set_protocol_code(value);
  // @@protoc_insertion_point(field_set:pb_common.req_head.protocol_code)
}
inline ::int32_t req_head::_internal_protocol_code() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.protocol_code_;
}
inline void req_head::_internal_set_protocol_code(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.protocol_code_ = value;
}

// optional int32 data_len = 2;
inline bool req_head::has_data_len() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void req_head::clear_data_len() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.data_len_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t req_head::data_len() const {
  // @@protoc_insertion_point(field_get:pb_common.req_head.data_len)
  return _internal_data_len();
}
inline void req_head::set_data_len(::int32_t value) {
  _internal_set_data_len(value);
  // @@protoc_insertion_point(field_set:pb_common.req_head.data_len)
}
inline ::int32_t req_head::_internal_data_len() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.data_len_;
}
inline void req_head::_internal_set_data_len(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.data_len_ = value;
}

// -------------------------------------------------------------------

// req_test

// optional int32 n1 = 1;
inline bool req_test::has_n1() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void req_test::clear_n1() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.n1_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t req_test::n1() const {
  // @@protoc_insertion_point(field_get:pb_common.req_test.n1)
  return _internal_n1();
}
inline void req_test::set_n1(::int32_t value) {
  _internal_set_n1(value);
  // @@protoc_insertion_point(field_set:pb_common.req_test.n1)
}
inline ::int32_t req_test::_internal_n1() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.n1_;
}
inline void req_test::_internal_set_n1(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.n1_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb_common


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_pb_5fcommon_2eproto_2epb_2eh
